config/routes.rb
Qqq::Application.routes.draw do
  get "demo/index"
  get "demo/result"
  get "demo/api_weather"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  def index

  end

  def result
    @forecast = calculate_weather(get_data_for_weather[0], get_data_for_weather[1])
  end

  def api_weather
    #TODO make it work :)
    render json:  @forecast[:daily][:data]
  end

  private

  def get_data_for_weather
    @geocoder = Geocoder.search(params[:name])
    @geocoder[0].data["geometry"]["location"].values
  end

  def calculate_weather(lat, lgn)
    ForecastIO.forecast(lat, lgn,
                        params: { units: 'si',
                                  exclude: 'minutely,hourly,flags,alerts'})

  end




  def get_location
    @lat_lgn = cookies[:lat_lgn].split("|").class
    puts @lat_lgn

  end



  def get_random_data
    data = [
        [53.2000, 13.000],
        [3,4],
        [5,6]
    ].sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper

  def get_data_forecast
    if @forecast[:daily][:data].nil?
      []
    else
      @forecast[:daily][:data].each do |p|
        {
            time: p,
            summary: p,
            sunriseTime: p,
            sunsetTime: p,
            temperatureMax: p,
        }

      end
    end
  end
end

app/views/demo/index.html.erb
<h1>Demo#index</h1>
<p>Find me in app/views/demo/index.html.erb</p>

<% unless @lat_lgn %>
    <script>
      getGeolocation();
    </script>
<% end %>

<%= form_tag demo_result_path, method: :get do %>
    <%= text_field_tag "name", params[:name] %>
    <%= submit_tag %>
<% end %>

app/views/demo/result.html.erb
<p>Result for: <%= params[:name] %></p>

<% @forecast[:daily][:data].each do |v| %>
   <% date = Date.strptime("#{v["time"]}", "%s") %>
   <p>Day <%= date.day %>, Month: <%= date.month %></p>
    <p><strong>Summary: <%= v["summary"] %></strong></p>
    <div>
      <p>Temperature min: <%= v["temperatureMin"] %></p>
      <p>Temperature max: <%= v["temperatureMax"] %></p>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qqq</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>